### ISSUE TITLE
Download url is deprecated

### ISSUE THREAD

**Issue by mamoit** [cowops/debian-predictionio#1]
The URL `http://download.prediction.io/PredictionIO-{{ predictionio.version }}.zip` is down.
Should use: `https://github.com/PredictionIO/PredictionIO/archive/v{{ predictionio.version }}.zip`

**Comment by loranger** [comment]
This role is rather old, a good cleaning would be useful.
Meanwhile, I've updated the download url (and sync'd with galaxy).
Thanks !

**Comment by mamoit** [comment]
Thanks, and you are right, I just noticed the url won't change a thing, there is no `setup.sh` in the new zip file.
